export enum EventCategory {
  ENTERTAINMENT = 'ENTERTAINMENT',
  EDUCATION = 'EDUCATION',
  SPORTS = 'SPORTS',
  BUSINESS = 'BUSINESS',
  SOCIAL = 'SOCIAL',
  TECHNOLOGY = 'TECHNOLOGY',
  ART = 'ART',
  OTHER = 'OTHER',
}
